### PR TITLE
Update GrottoNetworking.json for additional endpoints

### PR DESCRIPTION
**Pull request by Wind4Greg**
Added ecdsa-jcs-2019 and eddsa-jcs-2022 endpoints.

### CODE REVIEW

**Comment by PatStLouis** [comment]
I see the endpoints use a localhost address, shouldn't this use a publicly available endpoint?

**Review by BigBlueHat — APPROVED** [review]

**Review by aljones15 — CHANGES_REQUESTED** [review]
it would help if you specified a couple more endpoint related settings

per endpoint
```js
"supports": {
  "vc": ["2.0"]
}
```
that means your endpoint will only be run with the VC 2.0 test fixtures.

Two, you did not specify the `supportedEcdsaKeyTypes` as mentioned in the README: https://github.com/w3c/vc-di-ecdsa-test-suite?tab=readme-ov-file#implementation

```js
"supportedEcdsaKeyTypes": ["P-256"],
```

the suite does not know the curve/keyType that your issuer or verifier supports.
A verifier can support multiple `"supportedEcdsaKeyTypes"`, but an issuer should only support one, so please one issuer endpoint per curve/keyType/

**Comment by Wind4Greg** [comment]
Hi @aljones15 I  added     `"supports": {"vc": ["1.1", "2.0"]}` to all issuer and verifier entries.  It looks  like  all my ECDSA related entries have `"supportedEcdsaKeyTypes"`.

**Review by aljones15 — APPROVED** [review]
Sorry about the hold up and feel free to merge.

**Pull request merged**
